### ISSUE TITLE
Parameterize scripts to dynamically select addresses based on network

### ISSUE THREAD

**Issue by kautukkundan** [livepeer/arbitrum-lpt-bridge#36]
Many scripts rely on hardcoded addresses for execution. These should be modified such that the latest addresses are pulled either directly from environment or deployment data dynamically based on the selected network.

refer 
https://github.com/livepeer/arbitrum-lpt-bridge/pull/29#discussion_r775877603
https://github.com/livepeer/arbitrum-lpt-bridge/pull/25#discussion_r770066955

**Comment by yondonfu** [comment]
Fixed by #74
